# Generated by Django 6.0.4 on 2026-05-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='image_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
